In [73]:
import tensorflow as tf
import numpy as np
import json
loaded_model = tf.keras.models.load_model('./test_results/custom/cnn_complex/model_all.keras')
from keras.preprocessing import sequence



In [74]:
loaded_model

def load_text_vectorizer(path):
    config_json = path + "vectorizer_config.json"
    vocab_json = path + "vectorizer_vocab.json"
    
    with open(config_json, 'r') as f:
        config = json.load(f)
    
    with open(vocab_json, 'r') as f:
        vocab = json.load(f)
    
    vectorizer = tf.keras.layers.TextVectorization.from_config(config)
    vectorizer.set_vocabulary(vocab)
    
    return vectorizer

In [75]:
vectorizer = load_text_vectorizer('./test_results/custom/cnn_complex/')

raw_x_test = ['https://stackoverflow.com/questions/36404042/importerror-no-module-named-sklearn-python','https://www.tensorflow.org/responsible_ai/fairness_indicators/tutorials/Fairness_Indicators_TFCO_Wiki_Case_Study','https://wool-16t.pages.dev/wi0n0erary0mpalert048']


x_test = vectorizer(raw_x_test)
seq_length = 200


In [76]:
x_test = sequence.pad_sequences(x_test, maxlen=seq_length)


In [77]:
x_test


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0, 12,  2,  2, 11,  6,  6,  2,  4,
         9, 24,  5, 26,  3,  8, 25, 16,  5, 13,  9,  5, 14, 37, 18,  3,
         6,  2,  7,  5, 10,  6, 31, 23, 32, 22, 32, 22, 32, 15,  7, 14,
        11,  5,  8,  2,  3,  8,  8,  5,  8, 10,  5, 14,  5, 17, 18, 16,
         3, 10,  4, 14,  3, 17,  6, 24, 16,  3,  4,  8, 10, 11, 28,  2,
        12,  5, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,

In [78]:



y_pred = np.argmax(loaded_model.predict(x_test))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


In [79]:
loaded_model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


array([[0.69715506, 0.23107228],
       [0.70916307, 0.22787455],
       [0.6719666 , 0.2605838 ]], dtype=float32)

In [82]:
y_pred = np.argmax(loaded_model.predict(x_test), axis=1)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


array([0, 0, 0])